services:
  valkey:
    image: valkey/valkey:9-alpine
    container_name: bullmq-example-valkey
    command:
      - valkey-server
      - "--requirepass"
      - "oktomusic"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "oktomusic", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
